### ISSUE TITLE
Currently the sections in the 'More' pull down menu do not work from the All page

### ISSUE THREAD

**Issue by eggbean** [infokiller/web-search-navigator#253] opened 2021-02-24 07:43 UTC
The shortcuts for the sections that appear in the 'More' pull-down menu (which change according to the search results) do not work from the All page, but they do work from other sections. It doesn't matter that they work from the other sections as much as the All section, as you can always navigate to All, where it would be nice to always rely on the shortcuts working.

I love this extension and use it constantly every day, so I would like to see it working perfectly, but I know it must be a pain to keep it updated with every update Google makes.

**Comment by infokiller** [comment] 2021-02-24 07:54
Thanks for reporting, I'll try to fix it when I get a chance

**Comment by infokiller** [comment] 2021-09-03 15:57
@eggbean I just tested it and it mostly works for me:

- Books works
- Flight works
- Shopping works
- Finance is broken but will be fixed in 0.4.18 (due to be released soon)

Can you please check again and let me know if you see something different? If so, can you please provide a URL for testing?

**Comment by eggbean** [comment] 2021-09-04 20:25
Thanks for keeping this updated. I have been constantly using this, so I already know that it does not work perfectly, but usually works well enough. eg. https://www.google.com/search?q=open+house+london

* When on the Images tab, Maps doesn't work, but if I go back to All and then press M it works.
* Generally, anything in the More dropdown hardly ever works.
But those things are not very important anyway. The vast majority of my usage involves All and Images and less often News, Maps, Shopping and Videos and I think those tend to not be in the More drop down on relevant searches.

**Comment by infokiller** [comment] 2021-09-05 10:33
Thanks for the details @eggbean that's very helpful.
I discovered a race condition that indeed causes the links in the More dropdown to not always work (it's not consistent). I will try to fix this and release it in 0.4.18.

However, I can't reproduce the issue of navigating to the Maps tab when in the Images tab in this query. Can you please follow the steps in https://github.com/infokiller/web-search-navigator#building-for-development and see if the issue still exists? this will run the extension in a separate browser profile to verify that this issue is not related to any other extension. If it still reproduces, can you please post a screenshot of the search results when you're in the Images tab?

**Comment by infokiller** [comment] 2021-09-05 11:10
@eggbean I just fixed the More pulldown issue on master

**Closed** 2021-09-07 07:24 UTC
Labels: bug, fixed upstream
