### ISSUE TITLE
Periodic issues on search page

### ISSUE THREAD

**Issue by jinusean** [infokiller/web-search-navigator#299] opened 2021-09-04 04:21 UTC
Every now and then the extension does not work on the search page, and this is the output in the console.

```
search_engines.js:106 Uncaught (in promise) TypeError: Cannot read property 'offsetParent' of null
    at getSortedSearchResults (search_engines.js:106)
    at GoogleSearch.getSearchResults (search_engines.js:312)
    at SearchResultsManager.reloadSearchResults (main.js:41)
    at WebSearchNavigator.resetResultsManager (main.js:348)
    at WebSearchNavigator.initResultsNavigation (main.js:319)
    at WebSearchNavigator.init (main.js:167)
```

**Comment by infokiller** [comment] 2021-09-04 10:27
Duplicate of #297
Fixed on master, awaiting release for Chrome and Firefox

**Closed by infokiller** 2021-09-04 10:27 UTC
