### ISSUE TITLE
Startpage: next/previous navigation stops working once the selection goes to the last result on screen

### ISSUE THREAD

**Issue by GienekWspanialy** [infokiller/web-search-navigator#219] opened 2020-10-11 21:20 UTC
This happens (on my PC) only on some search phrases like [this one](https://www.startpage.com/do/dsearch?query=fiber+modality). 
Once the selection rectangle selects the last result on the screen (not on the page) the next/previous navigation stops working. The selection rectangle is not fully visible on screen – the bottom line is not visible while scroll bar remains on top. Other shortcuts still work, just not arrow up/down (or j/k). To restore normal behavior either scroll the page slightly to show full rectangle or navigate to next page.

**Comment by infokiller** [comment] 2020-10-16 13:02
@GienekWspanialy I can't reproduce this using your link: it works fine for me. I just added a [troubleshooting section](https://github.com/infokiller/web-search-navigator#troubleshooting) to the README, can you please follow it and report back?

**Comment by GienekWspanialy** [comment] 2020-10-17 18:58
@infokiller Thanks for the response. The extension is great and the bug is not problematic in real-life (I posted about it because it happened to me in like a third search after installation, otherwise I probably wouldn't notice it at all) :)

I'm not able to follow the troubleshooting section: after the last command that runs the "clean" browser (in my case it's Firefox) I can't enable experimental features – check-boxes seem to be clickable, but clicking them does not select them.

On the other hand I reproduced the bug after turning off all extensions I was able to reproduce the bug. It also seems to depend on the window size (and by proxy on a display resolution) – after "unmaximizing" the Firefox window the bug disappeared (with search query that caused problems previously). To reproduce with any Startpage search (requires a couple of takes, because its like pixel hunting):

1. Unmaximize the browser window with any search query.
2. Using arrows select one search result (I used something from the bottom of the screen, but I guess any should work).
3. Resize the browser window (bottom edge), so that the edge cuts a little bit of the rectangle (about 3 px above the bottom rectangle side).

Below is the screenshot with successful bug reproduction – at this setting moving the rectangle does not work (I forgot to take a screenshot before re-enabling all extensions, but I was able to reproduce with all extensions disabled):
![image](https://user-images.githubusercontent.com/38653331/96351370-5dda3b80-10aa-11eb-9f57-0fec5ceff4bd.png)

**Comment by infokiller** [comment] 2020-10-21 01:39
Thanks a lot for the detailed steps, that's very useful!
I'm pretty sure I know why this bug happens and I'll try to fix it.

Just one question about following the steps I added to the README: so you ran `yarn run web-ext run --source-dir src --target firefox-desktop`, but then what was the issue? what do you mean by experimental features?

**Comment by GienekWspanialy** [comment] 2020-10-21 17:09
Sure, glad I could help! :+1: 

Once the clean browser with Web Search Navigator runs, the Startpage support needs to be enabled. The screenshot below shows my current setup, so the boxes are already checked, but this was not possible in the clean browser instance run by the command – the boxes were not grayed-out (they seemed to be active) but clicking did not check any of them (I tried all of them). This might not even be related to the extension, but I'm too much of a layman to tell.
![image](https://user-images.githubusercontent.com/38653331/96753765-d8170280-13bf-11eb-8891-99a7b3dad059.png)

**Comment by infokiller** [comment] 2020-10-23 13:11
Thanks for the screenshot, this really helps!
I discovered a bug I introduced that caused the issue with enabling the optional permissions, and not it should be fixed.

**Comment by infokiller** [comment] 2020-10-23 15:38
Alright, I was able to reproduce the issue, but unfortunately it looks like it may be a Firefox bug. I added a workaround in the code which may fix it, although with a small cost: the bottom part of the search result may be hidden a bit by Firefox showing the URL of the selected result. Here's how it may look like:

![image](https://user-images.githubusercontent.com/10516814/97023620-70e38480-155e-11eb-8eeb-4564c3a5d490.png)

In the image above, one line in the description of the search result is hidden by the URL.

It would be great if you can test the mitigation. You can follow the same steps from [the troubleshooting section](https://github.com/infokiller/web-search-navigator#troubleshooting), but since you already did `git clone`, you can also switch to the directory `cd web-search-navigator` from where you cloned it, and then use `git pull` to get the latest changes I added.
Running `yarn run web-ext run --source-dir src --target firefox-desktop` should now work (I fixed the issue you had).

**Comment by GienekWspanialy** [comment] 2020-10-24 20:07
Yep, seems that both problems are solved. I was able to enable Startpage and I could no longer reproduce the bug that locked the rectangle.

Thank you! :+1: 

I'm not sure who should close the issue (I don't know the Github customs). I hope it's ok for me to leave it open, just in case you want to make some more changes related to this issue.

**Comment by infokiller** [comment] 2020-10-25 07:45
Great, thanks for testing it!
I'll close the issue after this is released to Firefox. I'll need to do some testing before to make sure everything still works, so it may take a few weeks.

**Comment by infokiller** [comment] 2020-10-25 07:47
BTW: as a workaround for your issue, I found the I can just hold the navigation key (for example the "Down" key) when it's stuck, and after 1-2 seconds it's no longer stuck. Maybe this will make things better for you till the fix is deployed.

**Comment by infokiller** [comment] 2020-11-18 10:22
@GienekWspanialy the new version is now released in both Chrome and Firefox

**Closed by infokiller** 2020-11-18 10:22 UTC
Labels: bug
