### ISSUE TITLE
Enhancement: YouTube support

### ISSUE THREAD

**Issue by asterisk37n** [infokiller/web-search-navigator#109] opened 2019-02-22 05:50 UTC
It would be beneficial if we can do the same thing on YouTube. In my opinion, I hope following two functions should be considered 
- Automatically focusing on search box when opening https://www.youtube.com/
- vim like shortcut (j/k) to go up and down youtube search result (ex. https://www.youtube.com/results?search_query=bach)

**Comment by infokiller** [comment] 2019-02-24 10:04
Duplicate of #82

**Closed** 2019-02-24 10:04 UTC
