### ISSUE TITLE
Feature request: Copy selected link

### ISSUE THREAD

**Issue by mikez** [infokiller/web-search-navigator#570] opened 2023-11-03 14:36 UTC
@infokiller, thank you for your work on WSN for over 6 years! Much appreciated.

**Request**:
In the search results, what do you think of adding a shortcut (e.g. `c`) to copy the highlighted link to the clipboard?
I find myself repeatedly clicking the vertical ellipsis `⋮` to then mark and copy the link.

If wanted, I can do a pull request. (The selector appears to be a simple `a[href]`.)

**Comment by infokiller** [comment] 2023-11-04 07:16
Hi @mikez I'm closing as duplicate of #549

**Closed by infokiller** 2023-11-04 07:16 UTC
