### ISSUE TITLE
[Bug Report] WSN gets stuck on Google's relevant questions box

### ISSUE THREAD

**Issue by MahdiNazemi** [infokiller/web-search-navigator#436] opened 2022-10-02 01:36 UTC
When searching for "BinaxNow" on Google, I can use the <kbd>J</kbd>/<kbd>K</kbd> keys to navigate the results until I get to Google's related questions. After that, I can use <kbd>J</kbd> to go up but cannot use <kbd>K</kbd> to go to the following results.

This happens on Brave 1.44.105 and WSN 0.4.22.
I can reproduce the issue on Firefox 105.0.1 too.

**Comment by infokiller** [comment] 2022-10-02 10:10
Thanks for reporting
I can't reproduce it because I don't get related questions (you may be on a google experiment or it's just geo differences), but I'll try more queries to reproduce it

**Comment by MahdiNazemi** [comment] 2022-10-07 00:57
You are welcome!

I don't get it either, even when I run the same query.
It was similar to the "People also ask" section that Google sometimes shows, but it had a COVID badge at the top.

**Comment by infokiller** [comment] 2022-11-01 20:18
@MahdiNazemi did you run into this again?
I'll close the issue for now since I can't reproduce, but if you are able to reproduce, please reopen, and a screenshot would be great.
Thanks

**Closed by infokiller** 2022-11-01 20:18 UTC
Labels: bug

**Comment by MahdiNazemi** [comment] 2022-11-01 20:41
Thanks for following up. I Googled the same query but never got the same related questions box again. I will take a screenshot if it happens again.
