### ISSUE TITLE
Arrow not visible for Google Search results

### ISSUE THREAD

**Issue by BorntraegerMarc** [infokiller/web-search-navigator#340] opened 2021-12-13 09:29 UTC
See attached screen recording:

The arrow is only visible for the Google News section. I was navigating down with the arrow keys and selected the `Coronavirus Test BAG` result. Even though the arrow was not visible I was still able to hit `Enter` and get to the web page

https://user-images.githubusercontent.com/7549295/145786376-ad56a1a9-7074-416a-9c52-318bc9120ddd.mov

**Comment by infokiller** [comment] 2021-12-13 09:32
I can't reproduce it so maybe Google put you in an experiment.
Can you please try the changes from https://github.com/infokiller/web-search-navigator/pull/339/files and report if it works? 
Note you can edit your CSS rules in the extension options, you don't need to build/install anything else.

**Comment by BorntraegerMarc** [comment] 2021-12-13 09:38
@infokiller With that CSS the Google Search works but the Google News not anymore 

https://user-images.githubusercontent.com/7549295/145787824-667724ef-5caf-4c52-b30f-c0566e0f7561.mov

**Comment by infokiller** [comment] 2021-12-13 09:44
Thanks! I will try to see if I can find a way to reproduce that.
If you have some experience with CSS and you can give me a configuration that works, that would be great.

**Comment by infokiller** [comment] 2022-02-20 01:35
@BorntraegerMarc are you still able to reproduce this issue?

**Comment by BorntraegerMarc** [comment] 2022-02-21 07:44
I've reset the extension to defaults now & I still have the behaviour as described in my [last comment](https://github.com/infokiller/web-search-navigator/issues/340#issuecomment-992277458)

https://user-images.githubusercontent.com/7549295/154910204-db2cf510-f1dd-4136-a5fb-c3137d90e232.mov

**Comment by infokiller** [comment] 2022-02-21 08:50
Thanks @BorntraegerMarc I'm able to reproduce it now- apparently this works when using dark mode so I missed it earlier:

![image](https://user-images.githubusercontent.com/10516814/154920212-1c3eaed4-e153-4bdd-b2bf-1da858267689.png)

**Comment by infokiller** [comment] 2022-05-07 01:07
@BorntraegerMarc   I believe this should be fixed now, if you can test the latest dev version and confirm it would be great, see https://github.com/infokiller/web-search-navigator#building-for-development

**Comment by BorntraegerMarc** [comment] 2022-05-09 08:58
Thx @infokiller! I’d rather wait for the official release & test then, though. (no time at the moment to build dev version)

**Comment by infokiller** [comment] 2022-05-09 17:38
@BorntraegerMarc no worries, the new version was just released (you will probably get it automatically in a few hours top)

**Closed** 2022-05-09 17:38 UTC
Labels: bug, fixed upstream

**Comment by BorntraegerMarc** [comment] 2022-05-10 06:47
Seems to be working now. Thx!
