### ISSUE TITLE
Cannot use J to pass Related Searches on Google SERPs

### ISSUE THREAD

**Issue by eggbean** [infokiller/web-search-navigator#509] opened 2023-04-22 06:13 UTC
I'm surprised that I can't find any mentions of this here, as I have come across this issue a few times in the last week or two: I can't navigate past Related Searches in the Google SERPs.

![image](https://user-images.githubusercontent.com/815311/233766238-61943ca3-9d95-43e1-8cf8-36bb251c4843.png)

**Comment by infokiller** [comment] 2023-04-28 05:21
Looks like a duplicate of #464

**Closed by infokiller** 2023-04-28 05:21 UTC
